### PR TITLE
Setuptools conversion

### PR DESCRIPTION
**Pull request by jhunkeler**

### CODE REVIEW

**Comment by SaOgaz** [comment]
Hey @jhunkeler, I'd like to merge this in with my dev branch (testing_plus), want to put in a PR against it instead of master?

**Comment by jhunkeler** [comment]
```
git checkout testing_plus
git remote add jhunk https://github.com/jhunkeler/stistools.git
git rebase jhunk/setuptools-conversion
```
**Endgame:**
When you merge _your PR_ to `master` it will close this because the commits for _this PR_ will be present in your branch. :+1:

**Comment by jhunkeler** [comment]
PS - The `relic` implementation here is old as hell.

I'll update it. Wait one.

**Comment by jhunkeler** [comment]
@SaOgaz done.

**Pull request merged**
