### PR TITLE
write extracted version to `version.py`

### PR DESCRIPTION
**Pull request by zacharyburnett**
resolves issue brought up in https://github.com/spacetelescope/stistools/pull/145#issuecomment-1448781211, where the `version` module wasn't being written after removing `relic`, which caused `autodoc` to not be able to import the module to create function definitions:
https://readthedocs.org/projects/stistools/builds/19599532/
```
Failed to import stistools.inttag.
Possible hints:
* ModuleNotFoundError: No module named 'stistools.version'
* KeyError: 'stistools'
```

### CODE REVIEW

**Comment by sean-lockwood** [comment]
I like the idea of building for pull requests -- enabled the setting.

**Comment by zacharyburnett** [comment]
> I like the idea of building for pull requests -- enabled the setting.

I might need to push another commit / force push the branch to trigger the webhook for this PR, standby

**Comment by zacharyburnett** [comment]
it looks like the fix worked: https://stistools--151.org.readthedocs.build/en/151/inttag.html

**Review by sean-lockwood — APPROVED** [review]
Thank you!

**Pull request merged**
