### PR TITLE
STIS-178: Remove scikit-image (skimage) dependency

### PR DESCRIPTION
**Pull request by sean-lockwood**
from stistools installation config.

### CODE REVIEW

**Comment by sean-lockwood** [comment]
@dougbrn -
Docs now build.  I temporarily added a new branch to RTD:
https://stistools.readthedocs.io/en/sl_stis-178/

This also includes Allyssa's defringing subarray docs that didn't build last time.

**Comment by sean-lockwood** [comment]
**Hold on...**

https://github.com/spacetelescope/stistools/blob/master/stistools/defringe/mkfringeflat.py#L4

mkfringeflat imports block reduce, which itself implicitly needs `scikit-image`:
```python
from astropy.nddata.utils import block_reduce
```

**Comment by pllim** [comment]
`block_reduce` is inhttps://github.com/astropy/astropy/blob/main/astropy/nddata/blocks.py now. Don't import it from `utils`.

Looking at your current set up, there are some outstanding technical debt that should be paid while you are doing this:

1. Use RTD v2 https://docs.readthedocs.io/en/stable/config-file/v2.html
2. Do not pull from astroconda , you definitely don't need it to build docs. Actually, do not use conda at all. Use pip to install all your doc dependencies.
3. Use `pyproject.toml`. Do not install using `setup.py install` anymore. Python org deprecated that. This is bigger than doc build but you need this modernized to install on RTD VM.

**Comment by sean-lockwood** [comment]
Looks like Jenkins is still running with Astropy 4.0.2.  Will add specification to the Jenkins file...

**Review by stscirij — APPROVED** [review]

**Pull request merged**
