### PR TITLE
Updated wx2d to conform to new astropy.io.fits API

### PR DESCRIPTION
**Pull request by tmonroeST**
Resolves an issue reported by a user for help call INC0135374 for wx2d task.

This crashed in astropy version 3.1.2 and pyraf (although not supported).
``
stistools.wx2d.wx2d('odk313a4q_flt.fits',output='odk313a4q_flt_out.fits')
``

### CODE REVIEW

**Comment by sean-lockwood** [comment]
The test files are both for CCD data, and the failed file is an NUV-MAMA dataset.  I think this means we need to:

- Increase the test suite to cover all three detectors
- Add code coverage to look for these untested spots in the code

**Comment by philhodge** [comment]
I think this change is perfectly reasonable; however, I don't think it's relevant to the problem that the user encountered.  The user has an old version of stistools, and his/her version is calling `phdu.header.update`.  The newer code (before the change in this PR) calls `phdu.header.set`, and `set` already does allow specifying that the keyword should be inserted before after some other keyword.

**Comment by sean-lockwood** [comment]
@philhodge :  Good catch!  It appears that just installing the master branch fixes the problem.  Code change not needed.  I suggest we withdraw this PR and update Conda with master soon.

**Comment by sean-lockwood** [comment]
Closing PR, as master in v1.2 solved this issue.

**Pull request closed without merging**
